
project_id = "nwisboqodsjdbnsiywax"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = false

# Fix the experimental section - use correct casing for keys
[experimental]
# Remove invalid keys or use correct casing
# trace = false
# multiThreadLoading = false

[functions.handle-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.analyze-face]
verify_jwt = true
